name: Sync multiple branches with main
on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    environment: "Branch 1"
    steps:
      - name: Read a token that is specific for an environment
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |-
          echo Checking if we can access this secret
          echo $MY_SECRET
          

