name: Sync multiple branches with main
on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: Branch 1
          - environment: Environment 2
    environment: ${{ matrix.environment }}
    steps:
      - name: Read a token that is specific for an environment
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |-
          echo Checking if we can access this secret
          if [ -z "${{ secrets.MY_SECRET }}" ]
          then
            echo Secret MY_SECRET is not set in secrets for this environment.
            ERROR=true
          fi
          

