name: Sync multiple branches with main
on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> branch1
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: branch1
          github_token: ${{ github.token }}

